### ISSUE TITLE
Thank you so much 😍😍

### ISSUE THREAD

**Issue by MirzaGorgAli** [Zero-One-Billion/PUBG_Hack_for_Emulator_in_CPP#2]
Hi sir, thank you for this awesome project.
I always say that no one does such a thing, to give to others a source even with tutorial for free that he can earn million dollars from it.
**There is no attribute to describe what you did.**
**_Thank you_**

SORRY ABOUT MY ENGLISH

**Comment by Zero-One-Billion** [comment]
Happy to hear that 😄 You are welcome, **knowlege** is for free for all
