### ISSUE TITLE
How to find View world?

### ISSUE THREAD

**Issue by MirzaGorgAli** [Zero-One-Billion/PUBG_Hack_for_Emulator_in_CPP#3]
Hi dude 
First as always thank you for this awesome project.
**Can you help me please to find view world and view matrix by myself ?**
I could find gnames gworld etc
But im stuck on these shi+ts
Please please help me sir

Thank you btw 😍

**Comment by MirzaGorgAli** [comment]
> Hi dude First as always thank you for this awesome project. **Can you help me please to find view world and view matrix by myself ?** I could find gnames gworld etc But im stuck on these shi+ts Please please help me sir
> 
> Thank you btw 😍

What is view world? I know view matrix cause of you 😙 but this is killing me
Can you please make tut on how to find view world?

Thanks

**Comment by Zero-One-Billion** [comment]
> > Hi dude First as always thank you for this awesome project. **Can you help me please to find view world and view matrix by myself ?** I could find gnames gworld etc But im stuck on these shi+ts Please please help me sir
> > Thank you btw 😍
> 
> What is view world? I know view matrix cause of you 😙 but this is killing me Can you please make tut on how to find view world?
> 
> Thanks


Use ldplayer emulator and try to dump the "lib4UE.so" file by https://github.com/kp7742/UE4Dumper 
use the dumped file at directory ./ue4dumper-lib-output/data/local/tmp
use IDA PRO to load and read the .so lib file
Uworld & Gnames will be like this
https://i.loli.net/2020/09/04/waosZvYN3RcJdne.png
https://i.loli.net/2020/09/04/vAqY1Bt63bV5CWh.png

**Comment by MirzaGorgAli** [comment]
Thank you so much 😍😍🙏
