### ISSUE TITLE
ESP::getViewWorld()

### ISSUE THREAD

**Issue by MirzaGorgAli** [Zero-One-Billion/PUBG_Hack_for_Emulator_in_CPP#4]
Hi dude
First of all thank you for this awesome repo and thank you for #3 you helped me a lot🙏😍

I did everything and I know what to do because of ur YT vids

**I know even how to calculate uworld and ... 
But they need viewworld offset!**

After some research on UC I couldnt any way to understand this: **ESP::getViewWorld()**

**How do you find BYTE pattern?**
You know game updates and I want to find it by myself

Im noob Can you help me?

Thanks a lot😍😍😍😍😍😍😍🙏🙏🙏🙏😗

**Comment by Zero-One-Billion** [comment]
There will be a next videos, be batient 😍

**Comment by MirzaGorgAli** [comment]
Dude I dont know what I can say!!
You are awesome 🤗❤❤
